---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ultron.2mind.dk
  resources:
  - ultronattendants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ultron.2mind.dk
  resources:
  - ultronattendants/finalizers
  verbs:
  - update
- apiGroups:
  - ultron.2mind.dk
  resources:
  - ultronattendants/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ultron.2mind.dk
  resources:
  - ultronobservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ultron.2mind.dk
  resources:
  - ultronobservers/finalizers
  verbs:
  - update
- apiGroups:
  - ultron.2mind.dk
  resources:
  - ultronobservers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ultron.2mind.dk
  resources:
  - ultrons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ultron.2mind.dk
  resources:
  - ultrons/finalizers
  verbs:
  - update
- apiGroups:
  - ultron.2mind.dk
  resources:
  - ultrons/status
  verbs:
  - get
  - patch
  - update
