# permissions for end users to edit ultrons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ultron-operator
    app.kubernetes.io/managed-by: kustomize
  name: ultron-editor-role
rules:
- apiGroups:
  - ultron.2mind.dk
  resources:
  - ultrons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ultron.2mind.dk
  resources:
  - ultrons/status
  verbs:
  - get
