apiVersion: ultron.2mind.dk/v1alpha1
kind: UltronAttendant
metadata:
  labels:
    app.kubernetes.io/name: ultron-operator
    app.kubernetes.io/managed-by: kustomize
  name: ultron-attendant
spec:
  container:
    name: "ultron-attendant"
    image: "ultron-attendant:latest"
    env:
      - name: ULTRON_ATTENDANT_CACHE_REFRESH_INTERVAL
        value: "15"
      - name: ULTRON_SERVER_REDIS_ADDRESS
        value: "redis-service.default.svc:6379"
      - name: ULTRON_SERVER_REDIS_PASSWORD
        value: "not2secure4u"
      - name: ULTRON_SERVER_REDIS_DATABASE
        value: "0"
      - name: EMMA_CLIENT_ID
        value: ""
      - name: EMMA_CLIENT_SECRET
        value: ""
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "250m"
