apiVersion: ultron.2mind.dk/v1alpha1
kind: UltronAttendant
metadata:
  labels:
    app.kubernetes.io/name: ultron-operator
    app.kubernetes.io/managed-by: kustomize
  name: ultron-attendant
spec:
  cacheRefreshInterval: 15
  container:
    name: "ultron-attendant"
    image: "ultron-attendant:latest"
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "250m"
  redis:
    address: "redis-service.default.svc:6379"
    database: 0
    password:      
      - name: "ultron-credentials"
        key: "ULTRON_SERVER_REDIS_PASSWORD"

