apiVersion: ultron.2mind.dk/v1alpha1
kind: Ultron
metadata:
  labels:
    app.kubernetes.io/name: ultron-operator
    app.kubernetes.io/managed-by: kustomize
  name: ultron
spec:
  container:
    name: "ultron"
    image: "ultron:latest"
    ports:
      - containerPort: 8443
        name: "https"
    env:
      - name: ULTRON_SERVER_CERTIFICATE_EXPORT_PATH
        value: "\\ultron-data\\ultron_ca_cert.pem"
      - name: ULTRON_SERVER_CERTIFICATE_ORGANIZATION
        value: "be-heroes"
      - name: ULTRON_SERVER_CERTIFICATE_COMMON_NAME
        value: "ultron-service.default.svc"
      - name: ULTRON_SERVER_CERTIFICATE_DNS_NAMES
        value: "ultron-service.default.svc,ultron-service,localhost"
      - name: ULTRON_SERVER_CERTIFICATE_IP_ADDRESSES
        value: "127.0.0.1"
      - name: ULTRON_SERVER_REDIS_ADDRESS
        value: "redis-service.default.svc:6379"
      - name: ULTRON_SERVER_REDIS_PASSWORD
        value: "not2secure4u"
      - name: ULTRON_SERVER_REDIS_DATABASE
        value: 0
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "250m"
  dataVolume:
    name: ultron-data
    persistentVolumeClaim:
      claimName: ultron-volume-claim
