apiVersion: ultron.2mind.dk/v1alpha1
kind: UltronObserver
metadata:
  labels:
    app.kubernetes.io/name: ultron-operator
    app.kubernetes.io/managed-by: kustomize
  name: ultron-observer
spec:
  container:
    name: "ultron-observer"
    image: "ultron-observer:latest"
    env:
      - name: ULTRON_SERVER_REDIS_ADDRESS
        value: "redis-service.default.svc:6379"
      - name: ULTRON_SERVER_REDIS_PASSWORD
        value: "not2secure4u"
      - name: ULTRON_SERVER_REDIS_DATABASE
        value: "0"
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "250m"
